$PWD/cinder/install/db.sh
$PWD/cinder/install/user.sh
$PWD/cinder/install/services.sh
$PWD/cinder/install/endpoints.sh
$PWD/cinder/install/packages.sh
$PWD/cinder/install/configure.sh
$PWD/cinder/install/volumes.sh
$PWD/cinder/install/sync.sh
$PWD/cinder/install/restart.sh
$PWD/cinder/install/types.sh
$PWD/cinder/verify.sh
